[build]
  base = "email-editor-ui"
  command = """
    npm install &&
    npm run build --workspace=email-editor-core &&
    npm run build
  """
  publish = ".next"

# Next.js support
[[plugins]]
  package = "@netlify/plugin-nextjs"
